# Example camera system configuration
# This file shows the format of the camera chain calibration output

cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [458.654, 457.296, 367.215, 248.375]
  resolution: [752, 480]
  rostopic: /cam0/image_raw

cam1:
  T_cn_cnm1:
  - [0.9999999999999998, 4.998958902716716e-17, 2.0291577889093294e-16, 0.11003342649999998]
  - [-5.551115123125783e-17, 0.9999999999999992, 5.274090697094731e-16, 0.0]
  - [-2.0677576697172372e-16, -5.274090697094731e-16, 0.9999999999999993, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [457.587, 456.134, 379.999, 255.238]
  resolution: [752, 480]
  rostopic: /cam1/image_raw
