#Accelerometer
accelerometer_noise_density: 0.006   # [m/s^2/sqrt(Hz)]
accelerometer_random_walk: 0.0002    # [m/s^3/sqrt(Hz)]

#Gyroscope  
gyroscope_noise_density: 0.0004      # [rad/s/sqrt(Hz)]
gyroscope_random_walk: 4.0e-06       # [rad/s^2/sqrt(Hz)]

#IMU update rate
update_rate: 200.0                   # [Hz]

#IMU ROS topic (reference IMU)
rostopic: /imu0/data

#IMU time offset (initial guess, will be optimized)
time_offset: 0.0                     # [s]
